package com.example.taskwork.dao

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import com.example.taskwork.model.Item

/*
The ItemDao is an abstract class whose implementation will be generated by Room.
This class contains the functions needed to run queries in the database.
Room provides useful annotations to ease the process of writing these functions.
 */
@Dao
interface ItemDao {
    /*
    The getPagedList() function returns a list of items after filtering
    it with the limit and offset parameters. This returns small chunks
    of data that will later be loaded by the Paging 3 library to be shown in the UI.
     */
    @Query("SELECT * FROM items ORDER BY id ASC LIMIT :limit OFFSET :offset")
    suspend fun getPagedList(limit: Int, offset: Int): List<Item>

    /*
    Insert used for inserting data into into dataset
     */
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insert(item: Item): Long
}