package com.example.taskwork.model

import androidx.room.Entity
import androidx.room.PrimaryKey
/*
Item is a simple data class.
There is an autogenerated primary key id that identifies different items in the db.
 */
@Entity(tableName = "items")
data class Item(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val name: String
)